"""empty message

Revision ID: 0111e1698284
Revises: 
Create Date: 2019-04-22 00:25:36.178424

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0111e1698284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('slug', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    # ### end Alembic commands ###
