"""empty message

Revision ID: 78fc6aa5e935
Revises: 0111e1698284
Create Date: 2019-04-22 00:45:06.475354

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '78fc6aa5e935'
down_revision = '0111e1698284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
